---
- name: Run awscliv2 role
  include_role:
    name: natemarks.awscli_v2

- include_tasks: anyconnect.yml

- name: Conditionally include onguard
  include_tasks: onguard.yml
  when: enable_onguard | bool

- name: Conditionally include crowdstrike
  include_tasks: crowdstrike.yml
  when: enable_crowdstrike | bool

- name: Conditionally include lansweeper
  include_tasks: lansweeper.yml
  when: enable_lansweeper | bool

- name: Conditionally include code42
  include_tasks: code42.yml
  when: enable_code42 | bool
